### ISSUE TITLE
Check PHP configuration

### ISSUE THREAD

**Issue by stephenyeargin** [nashvillest/puppet#6]
Apache doesn't appear to be loading the PHP module. A cursory glance indicates the PHP binary is not loaded on the box.

- [x] PHP installed
- [x] Apache properly recognizes `index.php` as an acceptable `DirectoryIndex`
- [x] `max_upload` directive set to `32M`
- [x] `max_post_size` directive set to `32M`

**Comment by cwage** [comment]
Done, verified by phpinfo():
```
upload_max_filesize	32M
post_max_size	32M
```

index.php is working as well
